[project]
name = "tiledbsoma-dask"
version = "0.0.1"
dependencies = [
    "anndata",
    "cellxgene-census",
    "click",
    "dask[array]",
    "numba",
    "scanpy",
    "scipy",
    "tiledb",
]

[project.scripts]
tdbs-dask = "tiledbsoma_dask.cli.main:main"
